create_distance – KohonenF08
create_distance Subroutine
19 statements
Source File
public subroutine create_distance(factory, type_, dist)
Class constructor
Type Bound
factory_distance
Arguments
Type Intent Optional Attributes Name
class(factory_distance) :: factory
A factory_distance object
character(len=*) :: type_
A character string with the type of distance to be instantiated
class(distance_base), allocatable :: dist
An allocatable distance_base object
Called by
Source Code
    subroutine create_distance(factory,type_,dist)
!========================================================================================
!! Class constructor
        class(factory_distance) :: factory
!! A `factory_distance` object
        character(len=*) :: type_
!! A character string with the type of distance to be instantiated
        class(distance_base),allocatable :: dist
!! An allocatable `distance_base` object
        select case(trim(type_))
          case('euclidean')
            !write(*,*) 'Euclidean distance';
            if(allocated(dist)) deallocate(dist);
            allocate(euclidean_distance :: dist);
          case('manhattan')
    !         !write(*,*) 'Manhattan distance allocated';
            if(allocated(dist)) deallocate(dist);
            allocate(manhattan_distance :: dist);
        case('max')
            if(allocated(dist)) deallocate(dist);
            allocate(max_distance :: dist);
          case default
            write(*,*) 'ERROR: the requested distance is not defined'
            stop
        end select
!
    end subroutine create_distance
Call graph
create_2lsom calls create_distance
create_som calls create_distance
set_cluster_layer calls create_distance
external_predict_map calls create_som
train_som calls create_som
train_two_level_som calls create_2lsom