create_random_sample – KohonenF08
create_random_sample Subroutine
12 statements
Source File
public subroutine create_random_sample(kohonen_map, input)
Subroutine to generate random values that serve as inputs to the SOM
Type Bound
self_organizing_map
Arguments
Type Intent Optional Attributes Name
class(self_organizing_map) :: kohonen_map
A self_organizing_map object
real(kind=wp), intent(out), dimension(:,:) :: input
A real array with the initial values of the prototypes
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, public :: nvar1
integer, public :: nvar2
integer, public :: i
integer, public :: j
Source Code
    subroutine create_random_sample(kohonen_map,input)
!========================================================================================
!! Subroutine to generate random values that serve as inputs to the SOM
    class(self_organizing_map) :: kohonen_map
!! A `self_organizing_map` object
    real(kind=wp),dimension(:,:),intent(out) :: input
!! A real array with the initial values of the prototypes
    integer :: nvar1,nvar2,i,j
!
    nvar1=size(input,1);
    nvar2=size(input,2);
    do i=1,nvar1;
        do j=1,nvar2;
            input(i,j)=kohonen_map%rnumber_grator%generate();
        end do
    end do
!
    end subroutine create_random_sample
Call graph
create_random_sample calls generate
create_som calls create_random_sample
external_predict_map calls create_som
train_som calls create_som