index2position – KohonenF08
index2position Subroutine
7 statements
Source File
public subroutine index2position(index_, nx, ny, nz, cx, cy, cz)
Subroutine to calculate the position ix,iy,iz inside a rectangular grid from index
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: index_
Integer variables, index_,nx,ny,nz
integer, intent(in) :: nx
Integer variables, index_,nx,ny,nz
integer, intent(in) :: ny
Integer variables, index_,nx,ny,nz
integer, intent(in) :: nz
Integer variables, index_,nx,ny,nz
integer, intent(inout) :: cx
Integer variables cx,cy,cz
integer, intent(inout) :: cy
Integer variables cx,cy,cz
integer, intent(inout) :: cz
Integer variables cx,cy,cz
Called by
Source Code
   subroutine index2position(index_,nx,ny,nz,cx,cy,cz)
   !========================================================================================
!!  Subroutine to calculate the position ix,iy,iz inside a rectangular grid from index
   integer,intent(in) :: index_,nx,ny,nz
!! Integer variables, index_,nx,ny,nz
   integer,intent(inout) :: cx,cy,cz
!! Integer variables cx,cy,cz
   !  write(*,*) index_,nx,ny,1+int((index_-1)/(nx*ny))
   cz=min(1+int((index_-1)/(nx*ny)),nz);
   cy=min(1+int((index_-1-(cz-1)*nx*ny)/nx),ny);
   cx=min(index_-(cz-1)*nx*ny-(cy-1)*nx,nx);
   !
   end subroutine index2position
Call graph
train_grid_layer calls index2position
update_weights calls index2position
train_2lsom calls train_grid_layer
train_two_level_som calls train_2lsom