init_genrand64 – KohonenF08
init_genrand64 Subroutine
10 statements
Source File
public subroutine init_genrand64(seed)
Initializes mt(nn) with a seed
Arguments
Type Intent Optional Attributes Name
integer(kind=i64), intent(in) :: seed
Called by
Source Code
  subroutine init_genrand64(seed)
!! Initializes mt(nn) with a seed
    implicit none
    integer(i64), intent(in) :: seed
    integer :: i
    mt(1) = seed
    do i = 1, nn-1
      mt(i+1) = 6364136223846793005_i64 * ieor(mt(i), ishft(mt(i), -62)) + i
    end do
    mti = nn
  end subroutine init_genrand64
Call graph
genrand64_real1 calls init_genrand64
genrand64_real2 calls init_genrand64
genrand64_real3 calls init_genrand64
init_by_array64 calls init_genrand64