kohonen_pattern_accessor – KohonenF08
kohonen_pattern_accessor Subroutine
5 statements
Source File
public subroutine kohonen_pattern_accessor(current_pattern, pattern_value)
Kohonen pattern accessor
Type Bound
kohonen_pattern
Arguments
Type Intent Optional Attributes Name
class(kohonen_pattern) :: current_pattern
A kohonen_pattern object
type(kohonen_prototype), intent(inout) :: pattern_value
Called by
Source Code
   subroutine kohonen_pattern_accessor(current_pattern,pattern_value)
!========================================================================================
!! Kohonen pattern accessor
      class(kohonen_pattern) :: current_pattern
!! A `kohonen_pattern` object
      type(kohonen_prototype),intent(inout) :: pattern_value
!
      pattern_value=current_pattern%pattern;
!
   end subroutine kohonen_pattern_accessor
Call graph
assign_input_to_clusters calls kohonen_pattern_accessor
evaluate_2lsom calls kohonen_pattern_accessor
find_bmu_grid calls kohonen_pattern_accessor
predict_2lsom calls kohonen_pattern_accessor
predict_som calls kohonen_pattern_accessor
train_grid_layer calls kohonen_pattern_accessor
train_som_data calls kohonen_pattern_accessor
external_predict_map calls predict_som
external_train_map calls train_som_data
train_2lsom calls assign_input_to_clusters, train_grid_layer
train_som calls train_som_data
train_two_level_som calls train_2lsom