mean – KohonenF08
mean Function
5 statements
Source File
public function mean(a) result(mn)
Function to calculate the mean of a real array
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(inout), dimension(:) :: a
A real array
Return Value real(kind=wp)
A real value with the calculated mean
Calls
Called by
Source Code
    function mean(a) result(mn)
!=============================================================================================
!! Function to calculate the mean of a real array
        real(kind=wp),dimension(:),intent(inout) :: a
!! A real array
        real(kind=wp) :: mn
!! A real value with the calculated mean
        mn=sum(a)/float(size(a));
!
    end function mean
Call graph
mean calls float
coefficient_of_variation calls mean, std
variance calls mean
std calls variance