position2index – KohonenF08
position2index Function
5 statements
Source File
public function position2index(ix, iy, iz, nx, ny) result(index_)
Function to calculate the index inside a rectangular grid from position ix,iy,iz
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ix
Integer variables ix,iy,iz,nx,ny
integer, intent(in) :: iy
Integer variables ix,iy,iz,nx,ny
integer, intent(in) :: iz
Integer variables ix,iy,iz,nx,ny
integer, intent(in) :: nx
Integer variables ix,iy,iz,nx,ny
integer, intent(in) :: ny
Integer variables ix,iy,iz,nx,ny
Return Value integer
Integer variable with the index
Called by
Source Code
   function position2index(ix,iy,iz,nx,ny) result(index_)
   !========================================================================================
!!   Function to calculate the index inside a rectangular grid from position ix,iy,iz
      integer,intent(in) :: ix,iy,iz,nx,ny
!! Integer variables ix,iy,iz,nx,ny
      integer ::index_
!! Integer variable with the index
   !*****
      index_=ix+(iy-1)*nx+(iz-1)*nx*ny
   !
   end function position2index
Call graph
calculate_distance_between_prototypes calls position2index
create_2lsom calls position2index
read_som_layer calls position2index
train_grid_layer calls position2index, calculate_distance_between_prototypes
update_weights calls position2index
train_2lsom calls train_grid_layer
train_two_level_som calls create_2lsom, train_2lsom