train_two_level_som – KohonenF08
train_two_level_som Subroutine
11 statements
Source File
public subroutine train_two_level_som(parameter_file)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: parameter_file
Calls
Source Code
    subroutine train_two_level_som(parameter_file)
    !==============================================================================
        character(len=*),intent(inout) :: parameter_file
        !
        call initialize_variables(parameter_file);
        !
        call my_som%create(som_parameters);
        !
        call my_som%train(input_patterns);
        !
        if(som_parameters(1)%train_option == 0) then
            call my_som%calculate_sum2_clusters_grid();
        endif
        !
        call my_som%destroy();
        !
        call release_variables();
    end subroutine train_two_level_som
Call graph
train_two_level_som calls calculate_sum2_clusters_grid, create_2lsom, destroy_2lsom, kohonen_pattern_create, kohonen_pattern_destroy, train_2lsom
calculate_sum2_clusters_grid calls get_prototype
create_2lsom calls create, calculate_distance_matrix, create_distance, create_random_sample, position2index
destroy_2lsom calls destroy
kohonen_pattern_create calls create
kohonen_pattern_destroy calls destroy
train_2lsom calls assign_input_to_clusters, train_cluster_layer, train_grid_layer
assign_input_to_clusters calls distance, kohonen_pattern_accessor
create_random_sample calls generate
train_cluster_layer calls get_prototype, float, distance, set_prototype
train_grid_layer calls get_prototype, position2index, float, distance, set_prototype, calculate_distance_between_prototypes, calculate_u_matrix, index2position, kohonen_pattern_accessor
calculate_distance_between_prototypes calls position2index
calculate_u_matrix calls distance