train_2lsom – KohonenF08
train_2lsom Subroutine
7 statements
Source File
public subroutine train_2lsom(kohonen_map, input_data)
Subroutine to train a two_level self_organized_map
Type Bound
two_level_self_organizing_map
Arguments
Type Intent Optional Attributes Name
class(two_level_self_organizing_map) :: kohonen_map
A two_level_self_organizing_map object
type(kohonen_pattern), intent(inout), dimension(:) :: input_data
A kohonen_pattern array
Calls
Called by
Source Code
   subroutine train_2lsom(kohonen_map,input_data)
   !========================================================================================
!!   Subroutine to train a two_level self_organized_map
      class(two_level_self_organizing_map) :: kohonen_map
!! A `two_level_self_organizing_map` object
      type(kohonen_pattern),dimension(:),intent(inout) :: input_data
!! A `kohonen_pattern` array
      call train_grid_layer(kohonen_map,input_data);
   !
      call train_cluster_layer(kohonen_map);
   !
      call kohonen_map%assign_input_to_clusters(input_data);
   !
   end subroutine train_2lsom
Call graph
train_2lsom calls assign_input_to_clusters, train_cluster_layer, train_grid_layer
assign_input_to_clusters calls distance, kohonen_pattern_accessor
train_cluster_layer calls float, distance, get_prototype, set_prototype
train_grid_layer calls float, distance, get_prototype, set_prototype, calculate_distance_between_prototypes, calculate_u_matrix, index2position, kohonen_pattern_accessor, position2index
calculate_distance_between_prototypes calls position2index
calculate_u_matrix calls distance
train_two_level_som calls train_2lsom