train_som – KohonenF08
train_som Subroutine
8 statements
Source File
public subroutine train_som(parameter_file)
Subroutine to train the SOM
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout) :: parameter_file
A character variable with the name of the parameter file
Calls
Source Code
    subroutine train_som(parameter_file)
    !==============================================================================
    !! Subroutine to train the SOM
        character(len=*),intent(inout) :: parameter_file
    !! A character variable with the name of the parameter file
        call initialize_variables(parameter_file);
        !
        call my_som%create(som_parameters);
        !
        call my_som%train(input_patterns);
        !
        call my_som%destroy();
        !
        call release_variables();
        !
    end subroutine train_som
Call graph
train_som calls error_stop, configure, create, delimiter, is_initialized, message, shutdown, startup, create_som, destroy_som, kohonen_pattern_destroy, train_som_data
create_som calls error_stop, create, calculate_coordinates, calculate_distance_matrix, create_distance, create_random_sample, position2index
destroy_som calls destroy
kohonen_pattern_destroy calls destroy
train_som_data calls get_prototype, calculate_distance_between_prototypes, calculate_u_matrix, find_best_match_unit, kohonen_pattern_accessor, update_weights
calculate_distance_between_prototypes calls position2index
calculate_u_matrix calls distance
create_random_sample calls generate
find_best_match_unit calls float, distance
update_weights calls get_prototype, position2index, dexp, set_prototype, index2position