position2index – KohonenF08
position2index Function
5 statements
Source File
public function position2index(ix, iy, iz, nx, ny) result(index_)
Function to calculate the index inside a rectangular grid from position ix,iy,iz
Type Bound
self_organized_map
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ix
Integer variables
integer, intent(in) :: iy
Integer variables
integer, intent(in) :: iz
Integer variables
integer, intent(in) :: nx
Integer variables
integer, intent(in) :: ny
Integer variables
Return Value integer
Integer variable with the required index
Called by
Source Code
    function position2index(ix,iy,iz,nx,ny) result(index_)
!========================================================================================
!! Function to calculate the index inside a rectangular grid from position ix,iy,iz
        integer,intent(in) :: ix,iy,iz,nx,ny
!! Integer variables
        integer ::index_
!! Integer variable with the required index
        index_=ix+(iy-1)*nx+(iz-1)*nx*ny;
!
    end function position2index
Call graph
calculate_distance_between_prototypes calls position2index
create_som calls position2index
external_train_map calls position2index, train_som_data
read_som calls position2index
update_weights calls position2index
external_predict_map calls create_som
train_som_data calls calculate_distance_between_prototypes, update_weights